theme: jekyll-theme-hacker
title: Sriharan Manogaran


author:
  name: Sriharan Manogaran
  email: sriharan72@gmail.com
  linkedin: sriharan16
  github: sriharan16
  medium: sriharan16
  instagram: darkman_16
  facebook: sriharan16897
  twitter: sriharan16897
